# Generated by Django 5.1 on 2024-11-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_userprofile_additional_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
