# Generated by Django 5.1 on 2024-11-19 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advice_generation', '0003_alter_conversation_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Locations', models.TextField()),
                ('conversations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_locations', to='advice_generation.conversation')),
                ('timestamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='advice_generation.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
