# Generated by Django 5.1 on 2024-11-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
