# Generated by Django 5.1 on 2024-11-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationServer', '0002_alter_locations_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='timestamp',
        ),
    ]
