# Generated by Django 5.1 on 2024-11-19 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationServer', '0003_remove_locations_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
